name: Terraform Plan

on:
  push:
    branches-ignore:
      - master

jobs:
  terraform-setup:
    uses: Vis-Rodrigues/workflow-template/.github/workflows/terraform-setup-composite-action.yml@main
    env:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-plan:
    uses: Vis-Rodrigues/workflow-template/.github/workflows/terraform-plan-composite-action.yml@main
    