name: Terraform Actions

on:
  push:

jobs:
  
  terraform:
    uses: Vis-Rodrigues/workflow-template/.github/workflows/terraform-action.yml@main
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}