name: Deploy S3 AWS

on:
  workflow_run:
    workflows: [Terraform Plan]
    branches: [master]
    types: [completed]
  push:
    branches:
      - master

jobs:

  terraform-apply:
    uses: Vis-Rodrigues/workflow-template/.github/workflows/terraform-apply-composite-action.yml@main
