name: Deploy S3 AWS

on:
  push:
    branches:
      - master

jobs:
  Terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      run: terraform init
      env:
        TF_ACTION_WORKING_DIR: '.'

    - name: Terraform Validate
      run: terraform validate 

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_ACTION_WORKING_DIR: '.'

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
        && terraform output > outputs-apply
      env:
        TF_ACTION_WORKING_DIR: '.'
    
    - name: Upload Output Apply
      uses: actions/upload-artifact@v3
      with:
        name: outputs-apply
        path: outputs-apply
        retention-days: 3
